services:
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - todo-network
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-to-do}
      DEFAULT_USER_EMAIL: ${DEFAULT_USER_EMAIL:-johnDoe@todoapp.com}
      DEFAULT_USER_NAME: ${DEFAULT_USER_NAME:-John Doe}
      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD:-password123}
    env_file:
      - .env
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - todo-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps:/usr/src/app/apps
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
    ports:
      - '${API_PORT:-3001}:3001'
      - '${DEBUG_PORT:-9229}:9229'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGODB_URI=${MONGODB_URI:-mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-to-do}?authSource=admin}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis123}
      - PORT=${API_PORT:-3001}
      - BULL_DASHBOARD_USER=${BULL_DASHBOARD_USER:-admin}
      - BULL_DASHBOARD_PASSWORD=${BULL_DASHBOARD_PASSWORD:-password123}
    env_file:
      - .env
    networks:
      - todo-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    command: pnpm run dev:api
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps:/usr/src/app/apps
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
    ports:
      - '${WORKER_PORT:-3003}:3003'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGODB_URI=${MONGODB_URI:-mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-to-do}?authSource=admin}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis123}
      - WORKER_PORT=${WORKER_PORT:-3003}
      - BULL_DASHBOARD_USER=${BULL_DASHBOARD_USER:-admin}
      - BULL_DASHBOARD_PASSWORD=${BULL_DASHBOARD_PASSWORD:-password123}
    env_file:
      - .env
    networks:
      - todo-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    command: pnpm run dev:worker
    restart: unless-stopped

  cronjobs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps:/usr/src/app/apps
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
    ports:
      - '${CRONJOBS_PORT:-3002}:3002'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGODB_URI=${MONGODB_URI:-mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-to-do}?authSource=admin}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis123}
      - CRONJOBS_PORT=${CRONJOBS_PORT:-3002}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
    env_file:
      - .env
    networks:
      - todo-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    command: pnpm run dev:cronjobs
    restart: unless-stopped

networks:
  todo-network:
    driver: bridge

volumes:
  redis_data:
  mongodb_data:
